AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda function for EC2 instance start/stop.

Metadata: 
  Name: ec2-instance-start-stop-python3

Parameters:
  InstanceID:
    Type: String
    Description: Set to EC2 InstanceID 
  CheckSchedule:
    Description: Set to Instance Check Schedule. Default [rate(1 day)]
    Type: String
    Default: "rate(1 day)"

Resources:
  InstanceStop:
    Type: AWS::Serverless::Function
    Properties:
      Description: EC2 Stop Function
      Handler: lambda_function.stop
      Runtime: python3.6
      MemorySize: 128
      Timeout: 300
      Policies:
        - Version: 2018-04-18
          Statement:
            - Effect: Allow
              Action:
                - ec2:Stop*
                - ec2:DescribeInstances*
              Resource: "*"
      CodeUri: ec2-actions-05e6402c-661a-47a5-b317-cc2adcb2a79b/ec2-actions.zip
      Environment:
        Variables:
          INSTANCE_ID: !Ref InstanceID
      Events:
        CheckInstanceScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref CheckSchedule

  InstanceStart:
    Type: AWS::Serverless::Function
    Properties:
      Description: EC2 Start Function
      Handler: lambda_function.start
      Runtime: python3.6
      MemorySize: 128
      Timeout: 300
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - ec2:Start*
                - ec2:DescribeInstances*
              Resource: "*"
      CodeUri: ec2-actions-05e6402c-661a-47a5-b317-cc2adcb2a79b/ec2-actions.zip
      Environment:
        Variables:
          INSTANCE_ID: !Ref InstanceID
      Events:
        CheckInstanceScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref CheckSchedule